sudo: false
language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar

before_cache:
  - source ./.travis/utils.sh backup-maven-repo

before_install:
  - source ./.travis/utils.sh prepare-build-bom $ENCRYPTION_PASSWORD

install:
  - "/bin/true"

script:
  - source ./.travis/build.sh

after_success:
  - source ./.travis/utils.sh restore-maven-repo
  - source ./.travis/qa.sh